[flyway]
locations = ["filesystem:./db/schema","filesystem:./db/undo", "filesystem:./db/repeatable"]
validateMigrationNaming = true
cleanDisabled = true

[environments.default]
url = "jdbc:postgresql://localhost:5432/racksstands"
user = "${env.DB_USER}"
password = "${env.DB_PASSWORD}"

[environments.production]
url = "jdbc:postgresql://prod-server:5432/racksstands"
user = "${env.PROD_DB_USER}"
password = "${env.PROD_DB_PASSWORD}"