# Database connection (using env variables)
flyway.url=jdbc:postgresql://localhost:5432/racksstands
flyway.user=${env.DB_USER}
flyway.password=${env.DB_PASSWORD}

# Migration locations
flyway.locations=filesystem:./db/schema
flyway.locations=filesystem:./db/repeatable
flyway.locations=filesystem:./db/undo