global using RacksStands.Framework.Persistence.Abstractions;
global using RacksStands.Module.UserManagement.DbContexts;
global using RacksStands.Module.UserManagement.DbContexts.Entities;
global using RacksStands.Framework.Persistence.Interceptors;
global using RacksStands.Framework.Persistence.Options;
global using RacksStands.Module.UserManagement.Constants;
global using RacksStands.Module.UserManagement.DbContexts.Repositories;
global using RacksStands.Module.UserManagement.Endpoints;
global using RacksStands.Framework.Modules.Bootstrap.Abstractions;
